seedtrack/src/SeedTrack/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SeedTrack.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Version"] = SeedTrack.Constants.Version;
            ViewData["Message"] = "CNLM Seed Tracker";
            ViewData["IsAdmin"] = User.IsInRole("Administrator"); 
            return View();
            //            return RedirectToAction("Index", "Species");
        }

        public IActionResult About()
        {
            ViewData["Version"] = SeedTrack.Constants.Version;
            ViewData["Message"] = "CNLM Seed Tracker";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "CNLM Seed Tracker";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
        //GET: /Index/AllTables
        [HttpGet]
        public IActionResult AllTables()
        {
            return View();
        }
        //GET: /Index/ComingSoon
        [HttpGet]
        public IActionResult ComingSoon()
        {
            return View();
        }

    }
}

seedtrack/src/SeedTrack/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeedTrack.Data;
using SeedTrack.Models.SeedLotModels;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Authorization;

namespace SeedTrack.Controllers
{
    [Authorize]
    public class PersonsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly DbContextOptions<ApplicationDbContext> _dbcOptions;
        private bool bWasContactPerson;
       public PersonsController(ApplicationDbContext context,
                        DbContextOptions<ApplicationDbContext> dbcOptions)

        {
            _context = context;
            _dbcOptions = dbcOptions;
            bWasContactPerson = false;
        }

        // GET: Persons
        [Authorize(Roles = "Administrator, PowerUser, Employee")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Person.Include(p => p.Organization);
            return View(await applicationDbContext.ToListAsync());

        }

        // GET: Persons/Details/5
        [Authorize(Roles = "Administrator, PowerUser, Employee")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationDBContext = _context.Person.Include(p => p.Organization);
            var person = await applicationDBContext.SingleOrDefaultAsync(m => m.PersonID == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: Persons/Create
        [Authorize(Roles = "Administrator, PowerUser")]
        public IActionResult Create(int? id)
        {
            List<SelectListItem> orgdropdownlistdata;
            if (null != id)
            {
                orgdropdownlistdata = MakeOrganizationDropDown((int)id);
            }
            else
            {
                orgdropdownlistdata = MakeOrganizationDropDown();
            }
            ViewData["OrgList"] = orgdropdownlistdata;
            ViewData["SelectedOrg"] = id;
            ViewData["InitialStateIndex"] = (Int32)States.WA;  // set to display Washington by default
            //find CNLM record to set as default
            ViewData["InitialOrgIndex"] = 0;
            string strTarget = "Center for Natural Lands Management";
            int indx = 0;
            foreach (SelectListItem itm in orgdropdownlistdata) { 
                if(itm.Text.Equals(strTarget,StringComparison.OrdinalIgnoreCase))
                    ViewData["InitialOrgIndex"] = indx;  // set to display CNLM by default
                indx++;
            }
            return View();
        }
        // GET: Persons/Create
        [Authorize(Roles = "Administrator, PowerUser")]
        public IActionResult CreateWOrg(int id)

        {
            List<SelectListItem> orgdropdownlistdata = MakeOrganizationDropDown(id);
            ViewData["OrgList"] = orgdropdownlistdata;
            ViewBag.OrgList = orgdropdownlistdata;
            ViewBag.SelectedOrg = id;
            ViewData["SelectedOrg"] = id;
            RouteValueDictionary args = new RouteValueDictionary();
            args.Add("id", id);
            ViewData["InitialStateIndex"] = (Int32)States.WA;  // set to display Washington by default
            return RedirectToAction("Create",args);
        }
            
        // POST: Persons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, PowerUser")]
        public async Task<IActionResult> Create(Person Item1)
        {
            if (ModelState.IsValid)
            {
                Int32 stateNo;
                stateNo = int.Parse(Item1.State);
                States eState = (States)stateNo;
                Item1.State = eState.ToString();
                Int32 countryNo = int.Parse(Item1.Country);
                Countries eCountry = (Countries)countryNo;
                Item1.Country = eCountry.ToString();

                _context.Add(Item1);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        // GET: Persons/Edit/5
        [Authorize(Roles = "Administrator, PowerUser")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationDbContext = _context.Person.Include(p => p.Organization);
            var person = await applicationDbContext.SingleAsync(m => m.PersonID == id);
            if (person == null)
            {
                return NotFound();
            }
            Organization organization = null;
            // retrieve Organization record
            if(null != person.OrganizationID)
            {
                organization = await _context.Organization.FindAsync(person.OrganizationID);
            }
            if (organization == null)
            {
                bWasContactPerson = false;
                person.IsContactPerson = false;
            }else {
                if (organization.ContactPersonID == person.PersonID)
                {
                    bWasContactPerson = true;
                    person.IsContactPerson = true;
                }
                else
                {
                    bWasContactPerson = false;
                    person.IsContactPerson = false;
                }
            }
            States eState = (States)Enum.Parse(typeof(States), person.State, true);
            ViewData["SelectedStateIndex"] = (Int32)eState;
            Countries eCountry = (Countries)Enum.Parse(typeof(Countries), person.Country, true);
            ViewData["SelectedCountryIndex"] = (Int32)eCountry;

            ViewData["OrganizationID"] = MakeOrganizationDropDown();

            return View(person);
        }

        // POST: Persons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, PowerUser")]
        public async Task<IActionResult> Edit(int id, [Bind("PersonID,Title,CellPhone,FirstName,LastName,Email,"+
            "OrganizationID,Phone,Extension,FirstLine,SecondLine,City,State,Country,ZipCode,IsContactPerson")] Person person)
        {
            if (id != person.PersonID)
            {
                return NotFound();
            }

            States eState = (States)Enum.Parse(typeof(States), person.State, true);
            ViewData["SelectedStateIndex"] = (Int32)eState;
            Countries eCountry = (Countries)Enum.Parse(typeof(Countries), person.Country, true);
            ViewData["SelectedCountryIndex"] = (Int32)eCountry;
            ViewData["OrganizationID"] = MakeOrganizationDropDown();
            // data comes back as selected index, need to convert to string for storage
            person.State = eState.ToString();
            person.Country = eCountry.ToString();

            if (ModelState.IsValid)
            {
                _context.Update(person);
                await _context.SaveChangesAsync();

                bool bIsContactPerson = person.IsContactPerson;
                if ((bIsContactPerson && !bWasContactPerson) || (!bIsContactPerson && bWasContactPerson))
                {
                    // Need to update organization data
                    var organization = await _context.Organization.FindAsync(person.OrganizationID);
                    if (organization != null)
                    {
                        organization.ContactPersonID = person.PersonID;
                        await _context.SaveChangesAsync();
                    }
                    return RedirectToAction("Index");
                }
            }
            return View(person);

        }

        // GET: Persons/Delete/5
        [Authorize(Roles = "Administrator, PowerUser")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationDBContext = _context.Person.Include(p => p.Organization);
            var person = await applicationDBContext.SingleOrDefaultAsync(m => m.PersonID == id);

            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: Persons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, PowerUser")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = await _context.Person.SingleOrDefaultAsync(m => m.PersonID == id);
            _context.Person.Remove(person);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool PersonExists(int id)
        {
            return _context.Person.Any(e => e.PersonID == id);
        }
        private List<SelectListItem> MakeOrganizationDropDown(int orgID=-1)
        {
            List<SelectListItem> orgdropdownlistdata = new List<SelectListItem>();
            var context = new ApplicationDbContext(_dbcOptions);

            using (ApplicationDbContext localcontext = new ApplicationDbContext(_dbcOptions))
            {

seedtrack/src/SeedTrack/Controllers/SpeciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeedTrack.Data;
using SeedTrack.Models;
using Microsoft.AspNetCore.Authorization;

namespace SeedTrack.Controllers
{
    [Authorize]
    public class SpeciesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SpeciesController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Species
        [Authorize(Roles = "Administrator, PowerUser, Employee, Guest")]
        public async Task<IActionResult> Index()
        {
            ProgramState.State = ProgramState.RunningState.Normal;
            return View(await _context.Species.ToListAsync());
        }

        // GET: Species/Details/5
        [Authorize(Roles = "Administrator, PowerUser, Employee, Guest")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var species = await _context.Species.SingleOrDefaultAsync(m => m.SpeciesID == id);
            if (species == null)
            {
                return NotFound();
            }

            return View(species);
        }

        // GET: Species/Create
        [Authorize(Roles = "Administrator, PowerUser")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Species/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, PowerUser")]
        public async Task<IActionResult> Create([Bind("SpeciesName,SpeciesID,Clade,Codon,FlowerPhoto,Genus,LifeCycle,PctCoverOneAdult,RestorationCharacteristics,RootStructure,SeedDormancyType,SeedPhoto,SeedlingPhoto,SubTaxa,Synonmyms,WholePlantPhoto")] Species species)
        {
            if (ModelState.IsValid)
            {
                ViewData["ErrorMessage"] = "";
                _context.Add(species);
                await _context.SaveChangesAsync();
                if(ProgramState.State == ProgramState.RunningState.CreatingSeedLot)
                {
                   return RedirectToAction("Create", "SeedLots");
                }
                return RedirectToAction("Index");
            }else  
            {
                var message = string.Join(" | ", ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));
                    ViewData["ErrorMessage"] = message;
            }
            return View(species);
        }

        // GET: Species/Edit/5
        [Authorize(Roles = "Administrator, PowerUser")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var species = await _context.Species.SingleOrDefaultAsync(m => m.SpeciesID == id);
            if (species == null)
            {
                return NotFound();
            }
            return View(species);
        }

        // POST: Species/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, PowerUser")]
        public async Task<IActionResult> Edit(int id, [Bind("SpeciesName,SpeciesID,Clade,Codon,FlowerPhoto,Genus,LifeCycle,PctCoverOneAdult,RestorationCharacteristics,RootStructure,SeedDormancyType,SeedPhoto,SeedlingPhoto,SubTaxa,Synonmyms,WholePlantPhoto")] Species species)
        {
            if (id != species.SpeciesID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(species);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpeciesExists(species.SpeciesID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(species);
        }

        // GET: Species/Delete/5
        [Authorize(Roles = "Administrator, PowerUser")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var species = await _context.Species.SingleOrDefaultAsync(m => m.SpeciesID == id);
            if (species == null)
            {
                return NotFound();
            }

            return View(species);
        }

        // POST: Species/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, PowerUser")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var species = await _context.Species.SingleOrDefaultAsync(m => m.SpeciesID == id);
            _context.Species.Remove(species);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool SpeciesExists(int id)
        {
            return _context.Species.Any(e => e.SpeciesID == id);
        }
    }
}

seedtrack/src/SeedTrack/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Center for Natural Lands Management";
    ViewData["SubTitle"] = "The Conservation Nursery";
    ViewData["Body1"] = "CNLM is known for superior stewardship of natural lands and rare species.  In Washington, CNLM focuses its effort on prairies, oak woodlands and freshwaters in the South Sound.  CNLM is a leader of regional efforts in the conservation of rare species and coordinates the South Sound Prairie Landscape Working Group, the Cascadia Prairie Oak Partnership and the conservation nursery.";
    ViewData["Body2"] = "We provide region-specific native plants and seeds to support habitat restoration in Western Washington, with a focus on grasslands and oak woodlands";
}
<p></p>
<img src="~/images/New Color logo with nameHighRes_no box (2014).png" alt="CNLM Logo" style="width:140px;height:168px;" />
<h2>@ViewData["Title"].</h2>


<p>@ViewData["Body1"]</p>
<img src="~/images/Violet Prairie landscape x03.jpg" left width="568" height="234" alt="Blooming Native Seed Field" />
    

<h3>@ViewData["SubTitle"]</h3>
<p>@ViewData["Body2"]</p>
<p></p>
<p></p>
<p></p>
@{

<p>Seed Tracker Version @ViewData["Version"]</p>
}
<p></p>
<p></p>


<script type="text/javascript">
 //   $(document).ready(function () {
//    jQuery(function ($) {
//        alert("jquery in about");
 //       $('#demo').dragtable();
//});
</script>

@*<div class="container-fluid">

    <div class="row">
        <div class="col-md-4" style="background-color:pink;">
            1 of 3
        </div>
        <div class="col-md-4" style="background-color:papayawhip;">
            2 of 3
        </div>
        <div class="col-md4" style="background-color:paleturquoise;"">
            3 of 3
        </div>
    </div>
    <div class="row">
        <div class="col-md-6" >
        </div>
    </div>
</div>
<table id="demo">
    <thead>
        <tr>
            <th>TIME</th>
            <th>%user</th>
            <th>%nice</th>
            <th>%system</th>
            <th>%iowait</th>
            <th>%idle</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>12:10:01 AM</td>
            <td>28.86</td>
            <td>0.04</td>
            <td>1.65</td>
            <td>0.08</td>
            <td>69.36</td>
        </tr>
        <tr>
            <td>12:20:01 AM</td>
            <td>26.54</td>
            <td>0.00</td>
            <td>1.64</td>
            <td>0.08</td>
            <td>71.74</td>
        </tr>
        <tr>
            <td>12:30:01 AM</td>
            <td>29.73</td>
            <td>0.00</td>
            <td>1.66</td>
            <td>0.09</td>
            <td>68.52</td>
        </tr>
    </tbody>
</table>
<script type="text/javascript">
$(document).ready(function() {
    $('#demo').dragtable();
});
</script>
<link rel="stylesheet" type="text/css" href="~/lib/dragtable/dragtable.css" />*@

seedtrack/src/SeedTrack/Views/Home/AllTables.cshtml
@{
    ViewData["Title"] = "Support Tables";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 style="color:#ffffff;">All Support Tables</h1>
            </div>
        </div>
    </div>
</div>
<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Farms</div>
            <div class="panel-body">
                <a asp-controller="FarmSites" asp-action="Index">Farm Sites </a><p></p>
                <a asp-controller="FarmBeds" asp-action="Create">Beds </a><p></p>
            </div>
        </div>
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Seeds</div>
            <div class="panel-body">
                <a asp-controller="Species" asp-action="Index">Species List </a><p></p>
                <a asp-controller="SeedLots" asp-action="Search1">Find Seedlot </a><p></p>
                <a asp-controller="Persons" asp-action="Index">People </a><p></p>
                <a asp-controller="Organizations" asp-action="Index">Organizations </a><p></p>
                <a asp-controller="CollectionSites" asp-action="Index">Wild Collection Sites</a><p></p>
                <a asp-controller="Level4Region" asp-action="Index">Level IV Regions</a><p></p>
                <a asp-controller="Level3Region" asp-action="Index">Level III Regions</a><p></p>
            </div>
        </div>
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Plugs</div>
            <div class="panel-body">
                <a asp-controller="PlugLots" asp-action="Index" class="">Find Pluglot</a><p></p>
                <a asp-controller="PlugSoils" asp-action="Index">Soil Mixes</a><p></p>
                <a asp-controller="PlugSoilComponents" asp-action="Index">Soil Components</a><p></p>
                <a asp-controller="PlugContainers" asp-action="Index">Plug Trays</a><p></p>
                <a asp-controller="PlugLocations" asp-action="Index" class="">Plug Locations</a><p></p>
                <a asp-controller="PlugLotObservations" asp-action="Create">New Observation</a><p></p>
                <a asp-controller="PlugMaintenanceActions" asp-action="Create">Maintenance Action</a><p></p>
            </div>

        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Calculation</div>
            <div class="panel-body">
                <a asp-controller="SeedLotTransactions" asp-action="RecalcAll" class="">Recalc all seedlot current and initial values</a><p></p>
                <a asp-controller="PlugLots" asp-action="RecalcAll" class="">Recalc all pluglot current  values</a><p></p>
                <div class="col-md-1">
                    <progress id="prgBar" value="70" max="100">70 %</progress>
                </div>

            </div>
        </div>
    </div>
</div>

seedtrack/src/SeedTrack/Views/Home/ComingSoon.cshtml
@{    ViewData["Title"] = "Coming Soon";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Coming Soon</h1>

seedtrack/src/SeedTrack/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    Center for Natural Land Management<br />
    120 Union Ave SE, Suite 215 <br />
    Olympia, WA 98501<br />
    Phone (360) 480-6105
</address>

<address>
    <strong>Support:</strong> <a href="mailto:ssmith@cnlm.org">ssmith@cnlm.org</a><br />
</address>

seedtrack/src/SeedTrack/Views/Home/Index.cshtml
@{
    ViewData["Title"] = ViewData["Message"] + " - " + ViewData["Version"];
}
<div class="jumbotron" style="background-color:rgb(88, 104, 91);">
    <div class="container">
        <div class="row">


            <div class="col-md-12">

                <div class="img-responsive col-md-2">
                    <img src="~/images/CNLMLogoNoText.png" height="75" width="150" alt="CNLM" style="opacity:0.9;filter:alpha(opacity=90);" />
                </div>
                <h2 style="color:#ffffff;">
                    <span class="glyphicon glyphicon-grain col-md-offset-2"></span>

                    @{
                        var Heading = ViewData["Message"];
                    }
                    @Heading
                    <span class="glyphicon glyphicon-grain"></span>
                </h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <p style="color:#ffffff;" class="col-md-offset-5 col-md-3">
                    <i>Version: @ViewData["Version"]</i>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="well clearfix">
            <div class="col-md-3">
                <a class="btn btn-success" asp-controller="SeedLots" asp-action="Search1">Find a Seed Lot</a>
            </div>
            <div class="col-md-3">
                <a class="btn btn-primary" asp-controller="Home" asp-action="ComingSoon">Current Availability</a>
            </div>
            <div class="col-md-3">
                <a class="btn btn-primary" asp-controller="Home" asp-action="ComingSoon">Build a Seed Mix</a>
            </div>
            <div class="col-md-3">
                <a class="btn btn-warning" asp-controller="Home" asp-action="AllTables">Support Tables</a>
            </div>
        </div>
    </div>
</div>


<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Farms</div>
            <div class="panel-body">
                <a asp-controller="Home" asp-action="ComingSoon">Field Maps </a><p></p>
                <a asp-controller="Home" asp-action="ComingSoon">Labor Records </a><p></p>
                @*<a href="~/Views/BedTransactions/PlantingRecords.cshtml">Planting Records</a>*@
                <a asp-controller="BedTransactions" asp-action="PlantingRecords">Planting Records </a><p></p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Nursery</div>
            <div class="panel-body">
                <a asp-controller="SeedLots" asp-action="Create">New Seed Lot </a><p></p>
                <a asp-controller="PlugLots" asp-action="Create"  asp-route-iAction="0">Sow Plug Lot</a><p></p>
                <a asp-controller="PlugLots" asp-action="Create" asp-route-iAction="5">Cold Strat Plug Lot </a><p></p>
                <a asp-controller="PlugLots" asp-action="Create" asp-route-iAction="3">Receive Plug Lot </a><p></p>
                <a asp-controller="PlugLots" asp-action="Search1">Find Plug Lot </a><p></p>
                <a asp-controller="Home" asp-action="ComingSoon">Allocation </a><p></p>
           </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Orders</div>
            <div class="panel-body">
                <a asp-controller="Home" asp-action="ComingSoon" class="">Create New Order</a><p></p>
                <a asp-controller="Home" asp-action="ComingSoon" class="">Fill Order</a><p></p>
                <a asp-controller="Home" asp-action="ComingSoon" class="">Production Plans</a><p></p>
            </div>

        </div>
    </div>
    
    <div class="col-md-3">
        <div class="panel panel-default" hidden id="ManagemntPanel">
            <div class="panel-heading">Administrator Tools</div>
            <div class="panel-body">
                <a asp-controller="Manage" asp-action="DeleteUser">Delete User</a><p></p>
                <a asp-controller="Manage" asp-action="ManageUserRoles">Manage User Roles</a><p></p>
                <a asp-controller="SeedLots" asp-action="RecalcCurrentQuantities">Recalculate Quantities</a><p></p>
            </div>
        </div>
    </div>
    
 </div>

<script>
    window.onload = function () {
        // show the admin tools depending on user's role.
        var test = @Json.Serialize(this.ViewData["IsAdmin"]);
        var x = document.getElementById("ManagemntPanel");
        if (false == test) {
            x.style.display = 'none';
        } else {
            x.style.display = 'block';
        }
    };

</script>