seedtrack/src/SeedTrack/Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeedTrack.Data;
using SeedTrack.Models.SeedLotModels;
using System.Collections;
using Microsoft.Extensions.Primitives;
using Microsoft.AspNetCore.Authorization;
using System.Linq.Expressions;

namespace SeedTrack.Controllers
{

    [Authorize]
    public class OrganizationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly DbContextOptions<ApplicationDbContext> _dbcOptions;
        public OrganizationsController(ApplicationDbContext context,
            DbContextOptions<ApplicationDbContext> dbcOptions)

        {
            _context = context;
            _dbcOptions = dbcOptions;
        }

        // GET: Organizations
        [Authorize(Roles = "Administrator, PowerUser, Employee")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Organization.Include(o => o.ContactPerson);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Organizations/Details/5
        [Authorize(Roles = "Administrator, PowerUser, Employee")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationDbContext = _context.Organization.Include(p => p.ContactPerson).Include(p => p.Persons);

            var organization = await applicationDbContext.SingleOrDefaultAsync(m => m.OrganizationID == id);

            //            var organization = await _context.Organization.SingleOrDefaultAsync(m => m.OrganizationID == id);
            if (organization == null)
            {
                return NotFound();
            }

            return View(organization);
        }

        // GET: Organizations/Create
        [Authorize(Roles = "Administrator, PowerUser")]
        public IActionResult Create()
        {
            //List<SelectListItem> stateList = new List<SelectListItem>();
            //Organization org = new Organization();
            //Address adr = new Address();
            //Person per = new Person();
            //Tuple<Organization, Address, Person, List<SelectListItem>> tuple = new Tuple<Organization, Address, Person, List<SelectListItem>>(org,adr,per,stateList);
            //return View(tuple);
            ViewData["InitialStateIndex"] = (Int32)States.WA;  // set to display Washington by default
            ViewData["OrgCreated"] = 0;
            return View();
        }

        // POST: Organizations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("OrganizationID,AddressID,ContactPersonID,OrganizationName,PhoneNumber")] Organization organization)
        //public async Task<IActionResult> Create(string OrganizationName,string PhoneNumber,string FirstLine,string SecondLine,
        //    string City,string State,string ZipCode, string Country)
        [Authorize(Roles = "Administrator, PowerUser")]
        public async Task<IActionResult> Create(Organization Item1, Person Item2)
        {

            if (ModelState.IsValid)
            {
                // check if org already exists
                Organization foundorg = await _context.Organization.FirstOrDefaultAsync(x => x.OrganizationName == Item1.OrganizationName);
                if(null != foundorg)
                {
                    ViewData["OrgCreated"] = 1;
                    ViewData["OrganizationID"] = foundorg.OrganizationID;
                    return View(new Tuple<Organization, Person>(Item1, Item2));
                }
                ViewData["OrgCreated"] = 0;
                Int32 stateNo;
                stateNo = int.Parse(Item1.State);
                States eState = (States)stateNo;
                Item1.State = eState.ToString();
                Int32 countryNo = int.Parse(Item1.Country);
                Countries eCountry = (Countries)countryNo;
                Item1.Country = eCountry.ToString();
                //organization.OrganizationName = Item1.OrganizationName;
                //organization.PhoneNumber = Item1.PhoneNumber;
                //organization.Extension = Item1.Extension;
                //organization.AddressID = address.AddressID;
                _context.Add(Item1);
                await _context.SaveChangesAsync();
                ViewData["OrgCreated"] = 1;
                ViewData["OrganizationID"] = Item1.OrganizationID;
                return View(new Tuple<Organization, Person>(Item1, Item2));

//                return RedirectToAction("Index");

            }
            return View(new Tuple<Organization, Person>(Item1,  Item2));
        }

        // GET: Organizations/Edit/5
        [Authorize(Roles = "Administrator, PowerUser")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //           var organization = await _context.Organization.SingleOrDefaultAsync(o => o.OrganizationID == id);

            var applicationDbContext = _context.Organization.Include(p => p.ContactPerson).Include(p => p.Persons);
            var organization = await applicationDbContext.SingleOrDefaultAsync(m => m.OrganizationID == id);
            //var organization = await _context.Organization.SingleOrDefaultAsync(m => m.OrganizationID == id);
            if (organization == null)
            {
                return NotFound();
            }
            if (null != organization.State)
            {
                States eState = (States)Enum.Parse(typeof(States), organization.State, true);
                ViewData["SelectedStateIndex"] = (Int32)eState;
            }else
            {
                // default to Washington for those not filled in
                ViewData["SelectedStateIndex"] = (Int32)States.WA;
            }
            if (null != organization.Country)
            {
                Countries eCountry = (Countries)Enum.Parse(typeof(Countries), organization.Country, true);
                ViewData["SelectedCountryIndex"] = (Int32)eCountry;
            }else
            {
                ViewData["SelectedCountryIndex"] = (Int32)Countries.USA;
            }
            List<SelectListItem> membersList = new List<SelectListItem>();

            foreach( Person p in organization.Persons)
            {
                SelectListItem selItem = new SelectListItem();
                selItem.Text = p.LastName + ", " + p.FirstName;
                selItem.Value = p.PersonID.ToString();
                if((null != organization.ContactPerson) && p.PersonID == organization.ContactPerson.PersonID)
                {
                    selItem.Selected = true;
                }else
                {
                    selItem.Selected = false;
                }
                membersList.Add(selItem);

            }
            ViewBag.Members = membersList;
 
            return View(organization);
        }

        // POST: Organizations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("OrganizationID,ContactPerson,OrganizationName,PhoneNumber,OranizationAddress.FirstLine,"+
        //    "OrganizationAddress.SecondLine,OrganizationAddress.City,OrganizationAddress.State,OrganizationAddress.ZipCode,"+
        //    "OrganizationAddress.Country,ContactPerson")] Organization organization)
        //        public async Task<IActionResult> Edit(int id,  Organization organization)
        [Authorize(Roles = "Administrator, PowerUser")]
        public async Task<IActionResult> Edit(Microsoft.AspNetCore.Http.IFormCollection values)
        {
            int id = Convert.ToInt32(values["OrganizationID"]);
            if (0 == id)
            {
                return NotFound();
            }
            Organization org = await _context.Organization.FindAsync(id);
            if (null != org)
            {
                org.OrganizationName = Convert.ToString(values["OrganizationName"]);
                org.PhoneNumber = Convert.ToString(values["PhoneNumber"]);
                org.Extension = Convert.ToString(values["Extension"]);
                org.Department = Convert.ToString(values["Department"]);
                StringValues strvals = values["ContactPersonID"];
                String strContactPersonID = strvals.ElementAt(1);
                org.ContactPersonID = Convert.ToInt32(strContactPersonID);
                org.FirstLine = Convert.ToString(values["FirstLine"]);
                org.SecondLine = Convert.ToString(values["SecondLine"]);
                org.City = Convert.ToString(values["City"]);
                // data for state and country come back as selected index, need to convert to string for storage
                int iState = Convert.ToInt32(values["State"]);
                org.State = ((States)(iState)).ToString();
                //org.State = Convert.ToString(values["State"]);
                int iCountry = Convert.ToInt32(values["Country"]);
                org.Country = ((Countries)(iCountry)).ToString();
                //org.Country = Convert.ToString(values["Country"]);
                org.ZipCode = Convert.ToString(values["ZipCode"]);

                if (ModelState.IsValid)
                {
                    try
                    {

seedtrack/src/SeedTrack/Views/Organizations/AddPerson.cshtml
@using SeedTrack.Models.SeedLotModels;

@model OrganizationAddPersonViewModel

@{
    ViewData["Title"] = "ReAssignPerson";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4>Assign Person</h4> 
 Assign/Reassign Person to 
@Model.organization.OrganizationName
<hr/>
<form asp-controller="Organizations" asp-action="AddPerson" method="post" class="form-horizontal">
    @Html.LabelFor(m => m.selectedIDs)
    <p class="small">(Hold Ctrl to select multiple)</p>
    @*@Html.DropDownListFor(m => m.selectedIDs,Model.userSelectList);*@
    @Html.ListBoxFor(m => m.selectedIDs, Model.userSelectList, new { Multiple = "multiple" })
    <hr />
    <input type="hidden" asp-for="orgID" />
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="Assign">
        <a href="~/Organizations/Details/@Model.organization.OrganizationID" class="btn btn-default" role="button">Cancel</a>
    </div>
</form>

seedtrack/src/SeedTrack/Views/Organizations/Create.cshtml
@using SeedTrack.Models.SeedLotModels;


@model Tuple<Organization,Person>


@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Organization</h2>
@if(@ViewBag.OrgCreated == 1){
    <label>Organization exists.  You can add members or go to Edit to change properties.</label>
}

<form asp-controller="Organizations" asp-action="Create" method="post" class="form-horizontal">
    <hr />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <div class="row">
            <label asp-for="Item1.OrganizationName" class="col-md-2 control-label"></label>
            <div class="col-md-4">
                <input asp-for="Item1.OrganizationName" class="form-control" />
                <span asp-validation-for="Item1.OrganizationName" class="text-danger" />
            </div>

            <label asp-for="Item1.PhoneNumber" class="col-md-2 control-label"></label>
            <div class="col-md-2">
                <input asp-for="Item1.PhoneNumber" class="form-control" />
                <span asp-validation-for="Item1.PhoneNumber" class="text-danger" />
            </div>
            <label asp-for="Item1.Extension" class="col-md-1 control-label"></label>
            <div class="col-md-1">
                <input asp-for="Item1.Extension" class="form-control" />
                <span asp-validation-for="Item1.Extension" class="text-danger" />
            </div>
        </div>
    </div>

    <!-- some space -->

    <div class="col-md-12" style="height:10px;"></div>

    <div class="row">
        <h4>Address:</h4>
    </div>
    <div class="row">
        <div class="form-group">
            <label asp-for="Item1.FirstLine" class="col-md-2 control-label"></label>
            <div class="col-md-8">
                <input asp-for="Item1.FirstLine" class="form-control" />
                <span asp-validation-for="Item1.FirstLine" class="text-danger" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <label asp-for="Item1.SecondLine" class="col-md-2 control-label"></label>
            <div class="col-md-8">
                <input asp-for="Item1.SecondLine" class="form-control" />
                <span asp-validation-for="Item1.SecondLine" class="text-danger" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <label asp-for="Item1.City" class="col-md-2 control-label"></label>
            <div class="col-md-4">
                <input asp-for="Item1.City" class="form-control" />
                <span asp-validation-for="Item1.City" class="text-danger" />
            </div>
            <label asp-for="Item1.State" class="col-md-1 control-label"></label>
            <div class="col-md-2">
                <select asp-for="Item1.State" class="form-control" id="StateList" asp-items="@Html.GetEnumSelectList<States>() "></select>
                <span asp-validation-for="Item1.State" class="text-danger" />

            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <label asp-for="Item1.ZipCode" class="col-md-2 control-label"></label>
            <div class="col-md-2">
                <input asp-for="Item1.ZipCode" class="form-control" />
                <span asp-validation-for="Item2.ZipCode" class="text-danger" />
            </div>
            <div class="col-md-2"></div>
            <label asp-for="Item1.Country" class="col-md-1 control-label"></label>
            <div class="col-md-2">
                <select asp-for="Item1.Country" asp-items="@Html.GetEnumSelectList<Countries>()" class="form-control"></select>
                <span asp-validation-for="Item2.Country" class="text-danger" />
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-9"> </div>
        <div class="col-md-1">
            <a href="Index" class="btn btn-default" role="button">Cancel</a>
        </div>
        <div class="col-md-1">
            <input type="submit" class="btn btn-primary" value="Save" id="OrgSaveBtn">
        </div>
        <div class="col-md-1">
            <a asp-action ="Edit" asp-route-id="@ViewBag.OrganizationID" class="btn btn-primary" value="Edit" id="OrgEditBtn">Edit </a>
        </div>

    </div>

    <!-- some space -->
</form>

    <div class="row">
        <div class="col-md-12" style="height:20px;"></div>
    </div>
    @*<input type="hidden" asp-for="Item1.OrganizationID" />*@

    <hr />

    <div class="form-group">
        <div class="col-md-3"><h4>Organization Members</h4></div>
        <div class="col-md-7"></div>
        <div class="col-md-2">
            <a id="AddPersonLink" asp-action="AddPerson" asp-route-id="@ViewBag.OrganizationID">+Add Person</a>
        </div>
    </div>


<table class="table" id="memberstable">
    <thead>
        <tr>
            <th>
                <label asp-for="Item2.LastName"></label>
            </th>
            <th>
                <label asp-for="Item2.FirstName"></label>
            </th>
            <th>
                <label asp-for="Item2.Phone"></label>
            </th>
            <th> Is Contact Person</th>
        </tr>
            @Html.DisplayFor(x=> x.Item1.Persons)
        @*@if(null != Model) { 
        @foreach (var item in .Item1.Persons)
            {
                <tr>
                    <td>
                        @item.FirstName
                    </td>
                </tr>

            }
        }*@
</table>



<div>
    <a href="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>

    function SetInitialState() {
        var sel = document.getElementById('StateList');
        var opts = sel.options;
        var selState = '@ViewBag.InitialStateIndex';
        sel.selectedIndex = selState;
    }

    $(document).ready(function () {
        SetInitialState();
        var y = document.getElementById('AddPersonLink');
        var z = document.getElementById('OrgSaveBtn');
        var x = document.getElementById('OrgEditBtn');
        var b = @ViewBag.OrgCreated;
        if (b == 1) {
            y.style.display = 'block';
            z.style.display = 'none';
            x.style.display = 'block';
        } else {
            y.style.display = 'none';
            z.style.display = 'block';
            x.style.display = 'none';
        }
    });
</script>

seedtrack/src/SeedTrack/Views/Organizations/Delete.cshtml
@model SeedTrack.Models.SeedLotModels.Organization

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Organization</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrganizationName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrganizationName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>
       <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Extension)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Extension)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

seedtrack/src/SeedTrack/Views/Organizations/Details.cshtml
@using SeedTrack.Models.SeedLotModels;
@using SeedTrack.Controllers;

@model Organization
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>


<h4>Organization</h4>
<hr />
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.OrganizationName)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.OrganizationName)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Department)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Department)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.PhoneNumber)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.PhoneNumber)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Extension)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Extension)
    </dd>
</dl>
<h4> Address</h4>
<div class="row">
    <div class="col-md-8 col-md-offset-1">
        @Html.DisplayFor(model => model.FirstLine)
    </div>
</div>
<div class="row">
    <div class="=col-md-8 col-md-offset-1">
        @Html.DisplayFor(model => model.SecondLine)
    </div>
</div>
<form class="form-inline">
    <div class="col-md-offset-1">
        @Html.DisplayFor(model => model.City),
        @Html.DisplayFor(model => model.State)
        @Html.DisplayFor(model => model.ZipCode)
        @Html.DisplayFor(model => model.Country)
    </div>
</form>
<h4> Contact Person</h4>
<form class="form-inline">
    @Html.DisplayFor(model => model.ContactPerson.FirstName)
    @Html.DisplayFor(model => model.ContactPerson.LastName)
</form>
<dl class="dl-horizontal">
    <dt>
        @Html.LabelFor(model => model.ContactPerson.Phone)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.ContactPerson.Phone)
    </dd>
    <dt>
        @Html.LabelFor(model => model.ContactPerson.CellPhone)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.ContactPerson.CellPhone)
    </dd>
</dl>
<h4>Members</h4>
@*<a class="col-md-offset-10" asp-action="AddPerson" asp-route-id="@Model.OrganizationID">Add Person</a>*@
<table class="table table-condensed table-striped">
    <tr>
        <th>@Html.DisplayNameFor(Model => Model.ContactPerson.LastName)</th>
        <th>@Html.DisplayNameFor(Model => Model.ContactPerson.FirstName)</th>
        <th>@Html.DisplayNameFor(Model => Model.ContactPerson.CellPhone)</th>
        <th>@Html.DisplayNameFor(Model => Model.ContactPerson.Phone)</th>
    </tr>
    @foreach (var item in Model.Persons)
            {
        <tr>
            <td>
                @item.LastName
            </td>
            <td>
                @item.FirstName
            </td>
            <td>
                @Html.DisplayFor(Model => Model.ContactPerson.CellPhone)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.ContactPerson.Phone)
            </td>
            <td>
                
@*               <a id="mybutton" href="@Url.Action("RemovePerson", "Organizations", new { id = item.PersonID })"> Remove </a>*@
 
            </td>
        </tr>

    }
</table>


<div>
    <a asp-action="Edit" asp-route-id="@Model.OrganizationID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

seedtrack/src/SeedTrack/Views/Organizations/Edit.cshtml
@using SeedTrack.Models.SeedLotModels;

@model Organization

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
<h4>Organization</h4>
<form asp-action="Edit" method="post">
    <div class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="OrganizationID" />
        <input type="hidden" asp-for="ContactPersonID" />

        <div class="form-group">
            <label asp-for="OrganizationName" class="control-label col-md-2"></label>
            <div class="col-md-6">
                <input asp-for="OrganizationName" class="form-control" >
                <span asp-validation-for="OrganizationName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Department" class="control-label col-md-2"></label>
            <div class="col-md-6">
                <input asp-for="Department" class="form-control">
                <span asp-validation-for="Department" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PhoneNumber" class="control-label col-md-2"></label>
            <div class="col-md-2">
                <input asp-for="PhoneNumber"  class="form-control" >
                <span asp-validation-for="PhoneNumber" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Extension" class="control-label col-md-2"></label>
            <div class="col-md-2">
                <input asp-for="Extension" class="form-control">
                <span asp-validation-for="Extension" class="text-danger" />
            </div>
        </div>
        <hr />
        <h4>Address:</h4>
        <div class="form-group">
            <label asp-for="FirstLine" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="FirstLine" class="form-control" />
                <span asp-validation-for="FirstLine" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="SecondLine" class="col-md-2 control-label"></label>
            <div class="col-md-6">
                <input asp-for="SecondLine" class="form-control" />
                <span asp-validation-for="SecondLine" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="City" class="col-md-2 control-label"></label>
            <div class="col-md-4">
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="State" class="col-md-2 control-label"></label>
            <div class="col-md-2">
                <select asp-for="State" class="form-control" asp-items="@Html.GetEnumSelectList<States>()" id="StateList" onload="SetSelectedState()"></select>
                <span asp-validation-for="State" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ZipCode" class="col-md-2 control-label"></label>
            <div class="col-md-2">
                <input asp-for="ZipCode" class="form-control" />
                <span asp-validation-for="ZipCode" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Country" class="col-md-2 control-label"></label>
            <div class="col-md-2">
                <select asp-for="Country" asp-items="@Html.GetEnumSelectList<Countries>()" class="form-control" id="CountryList"></select>
                <span asp-validation-for="Country" class="text-danger" />
            </div>
        </div>
        <hr />
        <h4>Contact Person:</h4>
        <div class="form-group">
            <div class="col-md-2"></div>
            <div class= "col-md-offset-2 col-md-2">
                <select asp-for="ContactPersonID"  class="form-control" asp-items=@ViewBag.Members ></select>
                <span asp-validation-for="ContactPersonID" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-6 col-md-6">
                <a href="~/Organizations/index"class="btn btn-default">Cancel</a>
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

<h4>Members</h4>
<a class="col-md-offset-10" asp-action="AddPerson" asp-route-id="@Model.OrganizationID">Reassign Person</a>
<a class="col-md-offset-10" asp-controller="Persons" asp-action="CreateWOrg" asp-route-id="@Model.OrganizationID">Create Person</a>
<table class="table table-condensed table-striped">
    <tr>
        <th>@Html.DisplayNameFor(Model => Model.ContactPerson.LastName)</th>
        <th>@Html.DisplayNameFor(Model => Model.ContactPerson.FirstName)</th>
        <th>@Html.DisplayNameFor(Model => Model.ContactPerson.CellPhone)</th>
        <th>@Html.DisplayNameFor(Model => Model.ContactPerson.Phone)</th>
    </tr>
    @foreach (var item in Model.Persons)
            {
        <tr>
            <td>
                @item.LastName
            </td>
            <td>
                @item.FirstName
            </td>
            <td>
                @Html.DisplayFor(Model => Model.ContactPerson.CellPhone)
            </td>
            <td>
                @Html.DisplayFor(Model => Model.ContactPerson.Phone)
            </td>
            <td>

                <a id="mybutton" href="@Url.Action("RemovePerson", "Organizations", new { id = item.PersonID })"> Remove </a>

            </td>
        </tr>

    }
</table>


<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<script>
    function SetSelectedState() {
        var sel = document.getElementById('StateList');
        var opts = sel.options;
        var selState = '@ViewBag.SelectedStateIndex'
        //alert(selState);
        sel.selectedIndex = selState;
    }
    function SetSelectedCountry() {
        var sel = document.getElementById('CountryList');
        var opts = sel.options;
        var selCountry = '@ViewBag.SelectedCountryIndex'
        sel.selectedIndex = selCountry;
    }

    $(document).ready(function () {
        SetSelectedState();
        SetSelectedCountry();
    });
</script>

seedtrack/src/SeedTrack/Views/Organizations/Index.cshtml
@model IEnumerable<SeedTrack.Models.SeedLotModels.Organization>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrganizationName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstLine)
            </th>
           <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OrganizationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department)
            </td>
           <td>
                @Html.DisplayFor(modelItem=>item.FirstLine)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.OrganizationID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.OrganizationID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.OrganizationID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>