seedtrack/src/SeedTrack/Models/FarmModels/BedTransactionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SeedTrack.Models.FarmModels
{
    public class BedTransactionViewModel
    {
        public BedTransaction bedTransaction { get; set; }
        public int? farmID { get; set; }
        public int iSelectedFarm { get; set; }
        public int iSelectedBed { get; set; }
        public int iSelectedBedID { get; set; }
        public int? bedID { get; set; }
        public string farmName { get; set; }
        public string bedTag { get; set; }
        public int? iSelectedAction {get;set;}
        public int? iTotalBedFeet { get; set; }

        // not used at the moment
        public IList<Plantings> lstPlantings { get; set; }
        public BedTransactionViewModel()
        {
            bedTransaction = new BedTransaction();
            farmID = 0;
            bedID = 0;
            iSelectedFarm = 0;
            iSelectedBed = 0;
            iSelectedBedID = 0;
            iSelectedAction = (int)BedTransactionType.Planted;
            iTotalBedFeet = 0;

        }
        public BedTransactionViewModel Clone()
        {
            BedTransactionViewModel mout = new BedTransactionViewModel();
            mout.farmID = this.farmID;
            mout.bedID = this.bedID;
            mout.iSelectedFarm = this.iSelectedFarm;
            mout.iSelectedBed = this.iSelectedBed;
            mout.iSelectedBedID = this.iSelectedBedID;
            mout.bedTransaction.BedFeet = this.bedTransaction.BedFeet;
            mout.bedTransaction.BedTransactionID = 0;
            mout.bedTransaction.FarmBedID = this.bedTransaction.FarmBedID;
            mout.bedTransaction.Notes = this.bedTransaction.Notes;
            mout.bedTransaction.PlantSpacing = this.bedTransaction.PlantSpacing;
            mout.bedTransaction.PlugLotID = this.bedTransaction.PlugLotID;
            mout.bedTransaction.PlugQuantity = this.bedTransaction.PlugQuantity;
            mout.bedTransaction.RowsPerBed = this.bedTransaction.RowsPerBed;
            mout.bedTransaction.SeedLotID = this.bedTransaction.SeedLotID;
            mout.bedTransaction.SeedQuantity = this.bedTransaction.SeedQuantity;
            mout.bedTransaction.TransactionDate = this.bedTransaction.TransactionDate;
            mout.bedTransaction.TransactionType = this.bedTransaction.TransactionType;
            mout.farmName = this.farmName;
            mout.bedTag = this.bedTag;
            mout.bedTransaction.CreatedBy = this.bedTransaction.CreatedBy;
            mout.bedTransaction.CreationDate = this.bedTransaction.CreationDate;
            mout.bedTransaction.ModifiedBy = this.bedTransaction.ModifiedBy;
            mout.bedTransaction.ModifiedDate = this.bedTransaction.ModifiedDate;
            return (mout);
        }

    }

    public class Plantings
    {
        public int? seedLotID { get; set; }
        public float? grams { get; set; }

    }
    public  class BedIDModel
    {
        public int? bedID { get; set; }
    }

}

seedtrack/src/SeedTrack/Controllers/BedTransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SeedTrack.Data;
using SeedTrack.Models;
using SeedTrack.Models.FarmModels;
using SeedTrack.Models.SeedLotModels;
using SeedTrack.Models.PlugLotModels;
using Microsoft.AspNetCore.Authorization;
using SeedTrack.Models.SeedLotTransactionModels;

namespace SeedTrack.Controllers
{
    [Authorize]
    public class BedTransactionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BedTransactionsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: BedTransactions
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.BedTransaction.Include(b => b.FarmBed).Include(b => b.PlugLot).Include(b => b.SeedLot);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: BedTransactions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bedTransaction = await _context.BedTransaction.SingleOrDefaultAsync(m => m.BedTransactionID == id);
            if (bedTransaction == null)
            {
                return NotFound();
            }

            return View(bedTransaction);
        }

        // GET: BedTransactions/Create
        [Authorize(Roles = "Administrator, PowerUser, Employee")]
        public IActionResult Create()
        {

            // find just the farms that have beds
            var res = from f in _context.FarmSite
                      join b in _context.FarmBeds on f.FarmSiteID equals b.FarmSiteID
                      select  f ;
            // and only one each of those please
            ViewData["FarmList"] = new SelectList(res.Distinct(),
                "FarmSiteID", "FarmName");
            ViewData["Error"] = "";
            // constructors do all the initialization of the bed transaction
            BedTransactionViewModel vw = new BedTransactionViewModel();
            // set some initial conditions
            //vw.bedTransaction.BedFeet = Constants.DEFAULT_BED_FEET_PLANTED;
            ////vw.bedTransaction.FarmBedID = 0;
            //vw.bedTransaction.PlantSpacing = Constants.DEFAULT_PLANT_SPACING;
            //vw.bedTransaction.PlugLotID = 0;
            //vw.bedTransaction.SeedLotID = 0;
            //vw.bedTransaction.PlugQuantity = Constants.DEFAULT_PLUG_QUANTITY;
            //vw.bedTransaction.RowsPerBed = Constants.DEFAULT_ROWS_PER_BED;
            //vw.bedTransaction.SeedQuantity = Constants.DEFAULT_SEED_QUANTITY;
            //vw.bedTransaction.TransactionType = BedTransactionType.Planted;
            //vw.bedTransaction.TransactionDate = DateTime.Now;
            //vw.iSelectedFarm = 0;
            //vw.iSelectedBed = 0;
            //vw.iSelectedAction = (int)BedTransactionType.Sowed;                //.Planted;
            //vw.iTotalBedFeet = 0;

            ViewData["SelectedFarmIndex"] = 0;
            ViewData["SelectedBedIndex"] = 0;
            return View(vw);
        }

      

        // POST: BedTransactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, PowerUser, Employee")]
        //       public async Task<IActionResult> Create(BedTransaction Item1, SeedLot Item2)
        public async Task<IActionResult> Create(BedTransactionViewModel model)
        //      public async Task<IActionResult> Create([Bind("BedTransactionID,BedFeet,FarmBedID,Notes,PlantSpacing,PlugLotID,PlugQuantity,RowsPerBed,SeedLotID,SeedQuantity,TransactionDate,TransactionType")] BedTransaction bedTransaction)
        {
            string strError="";
            // set up dropdowns etc.  for return
            var res = from f in _context.FarmSite
                      join b in _context.FarmBeds on f.FarmSiteID equals b.FarmSiteID
                      select f;
            // and only one each of those please
            var x = ViewData["SelectedFarmIndex"];
            ViewData["FarmList"] = new SelectList(res.Distinct(),
                "FarmSiteID", "FarmName");
            ViewData["Error"] = "";
            ViewData["SelectedFarmIndex"] = model.iSelectedFarm;
            ViewData["SelectedBedIndex"] = model.iSelectedBed;
            // null out the transaction id for return trips here, the server handles it
            model.bedTransaction.BedTransactionID = 0;
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            //BedTransaction bedTransaction = Item1;
            if (ModelState.IsValid)
            {
                model.bedTransaction.CreatedBy = User.Identity.Name;
                model.bedTransaction.CreationDate = DateTime.Now;
                model.bedTransaction.ModifiedBy = User.Identity.Name;
                model.bedTransaction.ModifiedDate = DateTime.Now;
                switch (model.bedTransaction.TransactionType)
                {
                    case BedTransactionType.Cleared:
                    case BedTransactionType.Removed:
                            model.bedTransaction.PlugLotID = null;
                            model.bedTransaction.BedFeet = 0;
                        // percent removed
                        if (model.bedTransaction.SeedLotID >= 0)
                        {
                            model.bedTransaction.SeedQuantity = (float)(model.bedTransaction.SeedLotID)/(float)100.0;
                        }
                            model.bedTransaction.SeedLotID = null;
                        break;
                    case BedTransactionType.Sowed:
                        model.bedTransaction.PlugLotID = null;
                        // if seedlot ID is passed it is actually the seedlot number and we need to correct it
                        try
                        {
                            if (null != model.bedTransaction.SeedLotID)
                            {
                                var seedLot = await _context.SeedLot.Where(m => m.SeedLotNumber == model.bedTransaction.SeedLotID).FirstOrDefaultAsync();
                                if (null != seedLot)
                                    model.bedTransaction.SeedLotID = seedLot.SeedLotID;
                            }
                        }
                        catch (Exception ex)
                        {
                            strError = "Failed to find seed lot number " + model.bedTransaction.SeedLotID.ToString() + " : " + ex.Message;
                            goto earlyerrorexit;
                        }
                        break;
                    case BedTransactionType.Planted:
                        try { 
                            if (null != model.bedTransaction.PlugLotID)
                            {
                                // change pluglot number to its ID - set the seedlot for provenance and plantings
                                var plugLot = await _context.PlugLot.Where(m => m.PlugLotNumber == model.bedTransaction.PlugLotID).FirstOrDefaultAsync();
                                if (null != plugLot) { 
                                    model.bedTransaction.PlugLotID = plugLot.PlugLotID;
                                    model.bedTransaction.SeedLotID = plugLot.SeedLotID;
                                }
                            }
                        }
                        catch (Exception ex)
                        {
                            strError = "Failed to find plug lot number " + model.bedTransaction.PlugLotID.ToString() + " : " + ex.Message;
                            goto earlyerrorexit;
                        }
                        break;
                    default:
                        break;
                }
                // make a copy of the model to return as we don't trust the scope of this one
                BedTransactionViewModel model2 = new BedTransactionViewModel();
                model2 = model.Clone();

                // now save the transaction
                try
                {
                    _context.Add(model.bedTransaction);
                    await _context.SaveChangesAsync();
                }
                catch(Exception ex)
                {
                    strError = "Failed to save bed transaction. " + ex.Message;
                    if(null != ex.InnerException) strError += " : " + ex.InnerException.Message;
                    goto earlyerrorexit;
                }
                // we have recorded the bed transaction but if we sowed we need to decrement
                // the seedlot, if we planted we need to decrement the pluglot
                if (model.bedTransaction.TransactionType == BedTransactionType.Sowed)
                {
                    SeedLotTransaction slt = new SeedLotTransaction();
                    slt.CreatedBy = User.Identity.Name;
                    slt.CreationDate = DateTime.Now;
                    slt.Notes = "Seeds used to sow bed " + model.farmName + " " + model.bedTag;
                    slt.TransactionType = SeedLotTransactionType.Disbursement;
                    slt.SeedLotID = (int)model.bedTransaction.SeedLotID;
                    slt.Quantity = (float)(-1.0 * model.bedTransaction.SeedQuantity);
                    slt.TransactionDate = DateTime.Now;
                    slt.OrganizationID = await GetCNLMOrgID();
                    try
                    {
                        _context.SeedLotTransaction.Add(slt);

seedtrack/src/SeedTrack/Views/BedTransactions/Delete.cshtml
@model SeedTrack.Models.FarmModels.BedTransaction

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BedTransaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BedFeet)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BedFeet)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlantSpacing)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlantSpacing)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlugQuantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlugQuantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RowsPerBed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RowsPerBed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SeedQuantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SeedQuantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TransactionDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TransactionDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TransactionType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TransactionType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

seedtrack/src/SeedTrack/Views/BedTransactions/Details.cshtml
@model SeedTrack.Models.FarmModels.BedTransaction

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>BedTransaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BedFeet)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BedFeet)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlantSpacing)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlantSpacing)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PlugQuantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PlugQuantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RowsPerBed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RowsPerBed)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SeedQuantity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SeedQuantity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TransactionDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TransactionDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TransactionType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TransactionType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BedTransactionID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

seedtrack/src/SeedTrack/Views/BedTransactions/EditBed.cshtml
@using SeedTrack.Models.FarmModels;
@using SeedTrack.Models.SeedLotModels;
@using Newtonsoft.Json;

@model FarmBed

@{
    ViewData["Title"] = "Bed Planting Record";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Bed Planting Record</h2>

<form asp-action="EditBed" asp-controller="BedTransactions" method="post">
    <div class="form-horizontal">
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group">
            <div class="col-md-1">Farm:</div>
            <div class="col-md-3">
                <strong> @ViewBag.FarmName</strong>
            </div>
            <div id="divBeds">
                <div class="col-md-1" id="lblBed">Bed Tag:</div>
                <div class="col-md-2">
                    <strong>
                        @ViewBag.BedTag
                    </strong>
                </div>
                <div id="divBedInfo">
                    <label class="col-md-1 control-label" id="lblBedLength">Length: </label>
                    <div class="col-md-1">
                        <input asp-for="Length" class="form-control" id="bed_length" disabled type="text">
                    </div>
                    <label class="col-md-1 control-label" id="lblBedWidth">Width: </label>
                    <div class="col-md-1">
                        <input asp-for="Width" class="form-control" id="bed_width" disabled>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="row">
                <label class="col-md-6 ">Current Planting: (Bed Feet : SeedLot Number : Taxon : Site : EcoRegion)</label>
            </div>
            <div class="row">
                <ul id="lstPlantings" class="lstPlantings" type="1"></ul>
            </div>
            <div class="form-group">
                <label class="control-label col-md-1"> Planted </label>
                <div class="col-md-1">
                    <input disabled id="iPlantedBedFeet" class="form-control" type="text" />
                </div>
                <label class="control-label  col-md-1"> Empty </label>
                <div class="col-md-1">
                    <input class="form-control" disabled id="iEmptyBedFeet" type="text" />
                </div>

            </div>
        </div>
        <div class="row">
            <label class="col-md-6 ">Bed History</label>
        </div>
        <div class="row">
            <label class="col-md-6 ">(Date   Action  [Bed Feet]  SeedLot PlugLot)</label>
        </div>

        <div class="form-group">
            <ul id="lstTrans" class="lstTrans" type="1"></ul>
        </div>
        <div class="form-group" hidden>
            <div class="col-md-offset-2 col-md-2">
                <input type="submit" value="Create" class="btn btn-primary" disabled />
            </div>
            <div class="col-md-1"></div>
        </div>

    </div>

</form>

<div >
    <div class="row">
        <div class="col-md-2">
            <a asp-controller="BedTransactions" asp-action="Create" >Action for different bed </a>
        </div>
        <div class="col-md-2">
            <a asp-controller="BedTransactions" asp-action="AddBedActions" asp-route-bedID="@Model.FarmBedID">Add action to this bed</a>
            </div>
        </div>
</div>


<script>
    function ShowPlantings() {
        $(".lstPlantings").empty();
        var x= @Model.FarmBedID;
        var plantedBedFeet=0;
        var targetEmpty=jQuery('#iEmptyBedFeet');
        var targetPlanted = jQuery('#iPlantedBedFeet');
        var targetBedLength = jQuery('#bed_length');
        var bedLength = targetBedLength.attr("value");
        jQuery.get('/BedTransactions/GetCurrentPlanting/', { bedId: x }, function (data, status) {
            if ('success' == status) {
                $(data).each(function (index, val) {
                    plantedBedFeet += val.bedfeet;
                    $(".lstPlantings").append("<li>" + val.bedfeet + " : " + val.srcID + 
                        " : " + val.taxon + " : " + val.siteName + " : " + val.ecoRegion + "</li>");
                    //target.attr(("value"), totBedFeet);
                    //target.attr(("text"), totBedFeet);

                })
                var empty = bedLength - plantedBedFeet; 
                targetEmpty.attr(("value"), empty);
                targetEmpty.attr(("text"), empty);
                targetPlanted.attr(("value"), plantedBedFeet);
                targetPlanted.attr(("text"), plantedBedFeet);
            }
        });

        //target.attr(("value"), totBedFeet);
    }

    function ShowBedHistory(){
        $(".lstTrans").empty();
        var x= @Model.FarmBedID;
        var strTransType;
        var lotNumber;
        jQuery.get('/BedTransactions/GetTransactions/',{bedId: x}, function (data, status){
            if ('success' == status) {
                
                $(data).each(function (index, val) {
                    // TO DO
                    // set type string need to get the seedlot or pluglot number
                    switch(val.transactionType){
                        case 0:
                            strTransType='Planted';
                            break;
                        case 1:
                            strTransType='Sowed';
                            break;
                        case 2:
                            strTransType='Cleared';
                            break;
                        case 3:
                            strTransType='Removed';
                            break;
                    }
                    var d= new Date(val.transactionDate);
                    strDate = d.toLocaleDateString(); // + "  " + d.toLocaleTimeString();
                    // show in the list
                        $(".lstTrans").append("<li>" +strDate + " " +strTransType  + " [" +
                        val.bedFeet + "] : " + val.seedLotID + " : " + val.plugLotID  + "</li>");
                })
            }
        });
    };

    function AppendUrlParamTokens(url, params) {
        for (var param in params) {
            if (params[param] == null) {
                delete params[param];
            }
        }
        return url + "?" + jQuery.param(params);
    };
    function SeedLotLookup(inputItem) {
        ShowSeedLotInfo(true);
        jQuery.getJSON(AppendUrlParamTokens('@Url.Action("SeedlotNumberLookup", "BedTransactions")',
            { seedlotNumber: inputItem.value }),
            function (result) {
                var target = jQuery('#seedlotTaxon');
                try{
                    target.attr(("value"), result.taxon);
                    target = $('#seedlotSite');
                    target.attr(("value"), result.site);
                }
                catch (err) {
                    var strErr = err;
                }
            });
    };


    function GetBedDetails(ddl) {
        jQuery.getJSON(AppendUrlParamTokens('@Url.Action("GetFarmBedDetails", "BedTransactions")',
            { bedId: ddl.options[ddl.selectedIndex].value }),
            function (result) {
                var target = jQuery('#bed_length').attr('Value', result[0].length);
                var target = jQuery('#bed_width').attr('Value', result[0].width);
            });
        ShowBedDetails();
        Model.FarmBedID = ddl.options[ddl.selectedIndex].value;


    };

    $(document).ready(function () {
        $('input[type=datetime]').datepicker({
            dateFormat: "mm/dd/yy",
            changeMonth: true,
            changeYear: true,
            yearRange: "-10:+1"
        });

    });

    window.onload = function () {
        ShowPlantings();
        ShowBedHistory();
    };



    function ShowSeedLotInfo(bShow)
    {
        var x = document.getElementById('divSeedLotInfo');
        if (bShow)
            x.style.display = 'block';
        else
            x.style.display = 'none';
    }

    function ShowBedDetails() {
        var x = document.getElementById("divBedInfo");
        x.style.display = 'block';
        ShowPlantings();
    };


    //==================================================================

 

</script>


</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

seedtrack/src/SeedTrack/Views/BedTransactions/PlantingRecords.cshtml
@using SeedTrack.Models.FarmModels;
@using SeedTrack.Models.SeedLotModels;
@using Newtonsoft.Json;

@model BedIDModel

@{
    ViewData["Title"] = "Planting Records";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["bedID"] = Model.bedID;
}
<h2> Planting Records</h2>
<form asp-action="EditBed" asp-controller="BedTransactions" asp-route-bedID="@Model.bedID" method="get">

    <div class="form-horizontal">

        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Planting Records</div>
                <div class="panel-body">
                    <a asp-controller="BedTransactions" asp-action="Create">New Planting Record</a><p></p>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">View/Edit Bed</div>
                <div class="panel-body">
                    <div id="divForm">
                        <div class="form-group">
                            <label class="col-md-1 control-label">Farm</label>
                            <div class="col-md-3">
                                <select class="form-control" asp-items="@ViewBag.FarmList" id="selFarmList" onchange="UpdateBedList(this)"></select>
                            </div>
                            <label class="col-md-1 control-label" id="lblBed">Bed</label>
                            <div class="col-md-2">
                                @*<select class="form-control" id="selBedList" size="10" />*@
                                <select onchange="GetBedDetails(this)" id="selBedList"></select>
                            </div>
                            <div class="col-md-2"> </div>
                            <input type="submit" value="View Bed" class="btn btn-primary" />
                            @*<a asp-controller="BedTransactions" asp-action="EditBed" asp-route-bedID="@Model.bedID">Go </a> <p></p>*@
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <input id="inpBedID" asp-for="bedID" class="form-control" type="hidden" />
        <input class="form-control" id="vbBedID" value="@ViewBag.bedID" type="hidden" />

    </div>
    @*<div class="col=md-9"></div>*@
</form>
<script>
    window.onload = function () {
        $("#selFarmList").prop('selectedIndex', 0);
        $("#selBedList").prop('selectedIndex', 0);
        var farmlist = document.getElementById('selFarmList');
        UpdateBedList(farmlist);
    }

    function UpdateBedList(ddl) {
        jQuery.getJSON(AppendUrlParamTokens('@Url.Action("GetFarmBeds", "BedTransactions")',
            { farmId: ddl.options[ddl.selectedIndex].value }),
            function (result) {
                var target = jQuery('#selBedList');
                target.empty();
                jQuery(result).each(function () {
                    jQuery(document.createElement('option'))
                        .attr('value', this.value)
                        .text(this.text)
                        .appendTo(target);
                });
            });
    };

    function GetBedDetails(ddl) {
        // save the selected bed ID
        var val = ddl.options[ddl.selectedIndex].value;
        var c = document.getElementById('inpBedID');
        //alert(ddl.options[ddl.selectedIndex].value);
        c.value = ddl.options[ddl.selectedIndex].value;
        var b = document.getElementById('vbBedID');
        b.value = ddl.options[ddl.selectedIndex].value;
        //var b = jQuery('inpBedID').attr('value', ddl.options[ddl.selectedIndex].value);
        var target = jQuery('#vbBedID').attr('Value', val);

    };



    function AppendUrlParamTokens(url, params) {
        for (var param in params) {
            if (params[param] == null) {
                delete params[param];
            }
        }
        return url + "?" + jQuery.param(params);
    };

</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}